name: Minesweeper Bot

on:
  issues:
    types: [opened]

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Minesweeper Game
        uses: imfing/minesweeper-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
